require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.files")
require("user.cmp")
require("user.lsp")
require("user.status_line")
require("user.tabs")
require("user.auto_close")
require("user.treesitter")
require("user.telescope")
require("user.comment")
require("user.git")
require("user.terminal")

vim.cmd([[colorscheme catppuccin]])
